[agent]
  interval = "10s"

[[inputs.mqtt_consumer]]
  servers = ["tcp://mosquitto:1883"]
  topics = ["senzor/sht41", "senzor/scd40"]
  data_format = "json"

[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = "SvzxTVsbj9h6-Ux1pQl_TRMEYK39es1nITvVnUuXPjeiVfzrcWuORlBJYZmwN0fjjgM4jYsTT34zP1uPR5M8Rw=="
  organization = "iot"
  bucket = "levegominoseg"